[clock]
enabled = true
# Set this to the highest priority so it will start with the clock
# priority = 1
# Enables a twelve hour clock instead of the 24hr one
# Defaults to your lcoal format if unset
# twelve_hour = false

[mpris2]
enabled = true
# Set this so web browsers like Firefox or Chrome don't steal the focus of your real music player
# You can check what to put here by using tools like D-Feet
# preferred_player = "Lollypop"

[crypto]
enabled = true
# Valid choices are "gbp", "usd" and "eur"
# Default is USD
currency = "eur"
